export const vehicleYears = Array.from(
  { length: 30 },
  (_, i) => new Date().getFullYear() - i
);

export const vehicleMakes = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "Donkervoort",
  "DS",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "Geely",
  "Genesis",
  "GMC",
  "Great Wall",
  "Haval",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Li Auto",
  "Lifan",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Maserati",
  "Maxus",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Microcar",
  "Mitsubishi",
  "Morgan",
  "Morris",
  "Nio",
  "Nissan",
  "Noble",
  "Opel",
  "Ora",
  "Pagani",
  "Perodua",
  "Peugeot",
  "PGO",
  "Polestar",
  "Porsche",
  "Proton",
  "Qoros",
  "Redogo",
  "Renault",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "Saleen",
  "SEAT",
  "Seres",
  "Shuanghuan",
  "Skoda",
  "Smart",
  "Spyker",
  "Ssangyong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Tata",
  "Tazzari",
  "Think",
  "Tianqi",
  "Toyota",
  "Trabant",
  "Triumph",
  "Udacity",
  "Udm",
  "Uerdinger",
  "Ural",
  "Vada",
  "Venucia",
  "Viper",
  "Volkswagen",
  "Volvo",
  "Voyah",
  "Vvm",
  "Wagoneer",
  "Waltz",
  "Wey",
  "Wuling",
  "Xpeng",
  "Yangzi",
  "Yangtze",
  "Zacoe",
  "Zenos",
  "Zenvo",
  "Zetta",
  "Zeekr",
  "Zhejiang",
  "Zhonghua",
  "Zotye",
].sort();

export const vehicleModels: Record<string, string[]> = {
  Acura: ["ILX", "RDX", "TLX", "MDX", "NSX"],
  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
  ],
  BMW: [
    "116i",
    "118i",
    "120i",
    "3 Series",
    "5 Series",
    "7 Series",
    "X1",
    "X3",
    "X5",
    "X7",
  ],
  Chevrolet: [
    "Spark",
    "Sonic",
    "Cruze",
    "Malibu",
    "Impala",
    "Silverado",
    "Equinox",
    "Traverse",
    "Tahoe",
  ],
  Dodge: ["Dart", "Charger", "Challenger", "Durango"],
  Ford: [
    "Focus",
    "Fusion",
    "Mustang",
    "Escape",
    "Edge",
    "Ranger",
    "F-150",
    "Expedition",
  ],
  GMC: ["Sierra", "Canyon", "Terrain", "Acadia", "Yukon"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "HR-V", "Odyssey", "Ridgeline"],
  Hyundai: [
    "i10",
    "i20",
    "i30",
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Palis",
  ],
  Jeep: ["Wrangler", "Compass", "Renegade", "Cherokee", "Grand Cherokee"],
  Kia: ["Rio", "Cerato", "Optima", "Sorento", "Telluride", "Niro"],
  Mazda: ["2", "3", "6", "CX-3", "CX-5", "CX-9"],
  "Mercedes-Benz": [
    "A-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
  ],
  Mitsubishi: ["Mirage", "Lancer", "Outlander", "Pajero"],
  Nissan: [
    "Versa",
    "Altima",
    "Maxima",
    "Qashqai",
    "X-Trail",
    "Rogue",
    "Murano",
    "Armada",
  ],
  Porsche: [
    "911",
    "Boxster",
    "Cayman",
    "Panamera",
    "Cayenne",
    "Macan",
    "Taycan",
  ],
  Renault: ["Clio", "Megane", "Scenic", "Espace", "Laguna", "Koleos"],
  Subaru: ["Impreza", "Legacy", "Outback", "Forester", "Crosstrek"],
  Suzuki: ["Swift", "Baleno", "Vitara", "SX4", "Jimny"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: [
    "Corolla",
    "Camry",
    "Prius",
    "RAV4",
    "Highlander",
    "Tacoma",
    "Tundra",
  ],
  Volkswagen: ["Polo", "Golf", "Jetta", "Passat", "Tiguan", "Touareg"],
  Volvo: ["S40", "S60", "S90", "XC40", "XC60", "XC90"],
};

export function getModelsForMake(make: string): string[] {
  return vehicleModels[make] || ["Unknown Model"];
}
